### ISSUE TITLE
something wrong with your example-data/initial_9x9.txt

### ISSUE THREAD

**Issue by fantianwen** [ihavnoid/leelaz-ninenine#5]
when I run the leelaz with the example weight file, I got crushed.

If you can check or provide another weight file work.
Thank you very much.

**Comment by ihavnoid** [comment]
The included file is for a 9x9 net.  You need a 13x13 initial net.  You probably need to create an initial net by writing some code - I did it by running the training process with zero input data (need some code hacking because normally it will refuse to do any training)
